import { useState, useEffect } from 'react';
import { Student, Observation, Evaluation } from '../lib/types';
import { getObservationsByStudent, getEvaluationsByStudent } from '../lib/storage';
import { formatStudentName } from '../lib/utils';
import { performanceLevelLabel } from '../lib/performanceLevel';
import { auth } from '../../firebase';
import { Button } from './ui/button';
import { ArrowLeft, Download, Printer, Loader2 } from 'lucide-react';
import { LaurelLogo } from './LaurelLogo';
import { format } from 'date-fns';

interface StudentDataExportProps {
  student: Student;
  onBack: () => void;
}

// Regulatory data export for an individual student (PIPEDA right of access -
// a parent/guardian can request everything Laurel Education holds about
// their child). Two formats are offered: a printable report a teacher can
// hand or email to a parent, and a raw JSON download with the same data for
// technical/audit purposes.
export function StudentDataExport({ student, onBack }: StudentDataExportProps) {
  const [observations, setObservations] = useState<Observation[]>([]);
  const [evaluations, setEvaluations] = useState<Evaluation[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      getObservationsByStudent(student.id),
      getEvaluationsByStudent(student.id),
    ]).then(([obs, evals]) => {
      setObservations([...obs].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()));
      setEvaluations([...evals].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()));
      setLoading(false);
    });
  }, [student.id]);

  const generatedAt = new Date();

  const handleDownloadJson = () => {
    const payload = {
      exportedAt: generatedAt.toISOString(),
      exportedBy: auth.currentUser?.email ?? null,
      student: {
        id: student.id,
        name: student.name,
        grade: student.grade,
        studentCode: student.studentCode ?? null,
        createdAt: student.createdAt,
      },
      observations: observations.map(o => ({
        id: o.id,
        type: o.type,
        subject: o.subject ?? null,
        content: o.content,
        tags: o.tags,
        performanceLevel: o.performanceLevel ?? null,
        timestamp: o.timestamp,
      })),
      evaluations: evaluations.map(e => ({
        id: e.id,
        date: e.date,
        generatedText: e.generatedText,
        strengths: e.strengths,
        areasForImprovement: e.areasForImprovement,
      })),
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const safeName = formatStudentName(student.name).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    a.href = url;
    a.download = `${safeName}-data-export-${format(generatedAt, 'yyyy-MM-dd')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <Loader2 className="w-8 h-8 animate-spin text-[#6B5FE4]" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="print:hidden bg-gradient-to-r from-[#1A1A40] to-[#6B5FE4] text-white p-4 flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-3">
          <Button size="sm" onClick={onBack} className="text-white hover:bg-white/20">
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <LaurelLogo height="sm" inverted={true} showProductName />
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" onClick={handleDownloadJson} className="bg-white/20 hover:bg-white/30 text-white gap-2">
            <Download className="w-4 h-4" />
            Download JSON
          </Button>
          <Button size="sm" onClick={() => window.print()} className="bg-white text-[#1A1A40] hover:bg-white/90 gap-2">
            <Printer className="w-4 h-4" />
            Print / Save as PDF
          </Button>
        </div>
      </div>

      <div className="max-w-2xl mx-auto p-6 print:p-0 bg-white text-gray-900">
        <div className="mb-6 pb-4 border-b-2 border-gray-200">
          <h1 className="text-2xl font-bold text-[#1A1A40] mb-1">Student Data Export</h1>
          <p className="text-sm text-gray-600">
            All information recorded for {formatStudentName(student.name)} in Laurel Education, as of{' '}
            {format(generatedAt, 'MMMM d, yyyy')}.
          </p>
          <p className="text-xs text-gray-400 mt-1">
            Generated by {auth.currentUser?.email ?? 'unknown user'} on {format(generatedAt, "MMMM d, yyyy 'at' h:mm a")}
          </p>
        </div>

        <section className="mb-6">
          <h2 className="text-sm font-semibold uppercase text-gray-500 mb-2">Student Information</h2>
          <dl className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
            <dt className="text-gray-500">Name</dt>
            <dd>{formatStudentName(student.name)}</dd>
            <dt className="text-gray-500">Grade</dt>
            <dd>{student.grade}</dd>
            {student.studentCode && (
              <>
                <dt className="text-gray-500">Student Code</dt>
                <dd>{student.studentCode}</dd>
              </>
            )}
            <dt className="text-gray-500">Record Created</dt>
            <dd>{format(new Date(student.createdAt), 'MMMM d, yyyy')}</dd>
          </dl>
        </section>

        <section className="mb-6">
          <h2 className="text-sm font-semibold uppercase text-gray-500 mb-2">
            Observations ({observations.length})
          </h2>
          {observations.length === 0 ? (
            <p className="text-sm text-gray-500">No observations recorded.</p>
          ) : (
            <div className="space-y-3">
              {observations.map(obs => (
                <div key={obs.id} className="border border-gray-200 rounded-lg p-3 break-inside-avoid">
                  <div className="flex items-center justify-between text-xs text-gray-500 mb-1">
                    <span>{format(new Date(obs.timestamp), 'MMMM d, yyyy - h:mm a')}</span>
                    <span>{obs.subject || 'General'} &middot; {obs.type}</span>
                  </div>
                  <p className="text-sm mb-1">{obs.content}</p>
                  {obs.performanceLevel && (
                    <p className="text-xs text-gray-500">Performance Level: {performanceLevelLabel(obs.performanceLevel)}</p>
                  )}
                  {obs.tags.length > 0 && (
                    <p className="text-xs text-gray-500">Tags: {obs.tags.join(', ')}</p>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>

        <section className="mb-6">
          <h2 className="text-sm font-semibold uppercase text-gray-500 mb-2">
            Report Commentary ({evaluations.length})
          </h2>
          {evaluations.length === 0 ? (
            <p className="text-sm text-gray-500">No saved report commentary.</p>
          ) : (
            <div className="space-y-4">
              {evaluations.map(evaluation => (
                <div key={evaluation.id} className="border border-gray-200 rounded-lg p-3 break-inside-avoid">
                  <p className="text-xs text-gray-500 mb-2">{format(new Date(evaluation.date), 'MMMM d, yyyy')}</p>
                  <p className="text-sm mb-2">{evaluation.generatedText}</p>
                  {evaluation.strengths.length > 0 && (
                    <p className="text-xs text-gray-600 mb-1">Strengths: {evaluation.strengths.join('; ')}</p>
                  )}
                  {evaluation.areasForImprovement.length > 0 && (
                    <p className="text-xs text-gray-600">Areas for Improvement: {evaluation.areasForImprovement.join('; ')}</p>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>

        <div className="pt-4 border-t text-xs text-gray-400">
          This document contains all personal information Laurel Education holds about{' '}
          {formatStudentName(student.name)} as of {format(generatedAt, 'MMMM d, yyyy')}.
        </div>
      </div>
    </div>
  );
}
